imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

best_it_ct_order_export:
    commercetools_client:
        id: '%commercetools.client_id%'
        project: '%commercetools.project%'
        secret: '%commercetools.client_secret%'
        scope: '%commercetools.scope%'
    filesystem: app.export.filesystem
    orders:
        with_pagination: true
        default_where:
            - 'syncInfo is empty'

framework:
    secret: '%secret%'

monolog:
    handlers:
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

oneup_flysystem:
    adapters:
        app.export.filesystem.adapter:
            local:
                directory: '%kernel.root_dir%/../var/export'

    filesystems:
        app:
            adapter: 'app.export.filesystem.adapter'
            alias: 'app.export.filesystem'
