services:
    app.commercetools.client:
        class: Commercetools\Core\Client
        factory: ['AppBundle\ClientFactory', createClient ]
        arguments:
        -   {
                client_id: '%app.commercetools.client.id%',
                client_secret: '%app.commercetools.client.secret%',
                project: '%app.commercetools.client.project%',
                scope: '%app.commercetools.client.scope%'
            }
        - '@cache.app'

    app.customer_factory:
        class: AppBundle\CustomerFactory
        arguments:
            - '@cache.app'
            - '@app.commercetools.client'

    app.exporter:
        class: AppBundle\Exporter
        arguments:
            - '@app.customer_factory'
            - '@app.filesystem'
            - '%app.orders.file_template%'
            - '@app.order_name_generator'
            - '@twig'

    app.order_visitor:
        class: AppBundle\OrderVisitor
        arguments:
            - '@app.commercetools.client'
            - '%app.orders.with_pagination%'

    app.order_name_generator:
        class: AppBundle\OrderNameGenerator
        arguments:
            - '%app.orders.name_scheme%'

    app.progress_bar_factory:
        class: AppBundle\ProgressBarFactory
